language: php

php:
  - 5.6
  - 7
  - 7.1
  - hhvm
  - nightly

sudo: false

install:
  - composer selfupdate
  - composer install
  - echo $TRAVIS_PHP_VERSION
  - if [ "$TRAVIS_PHP_VERSION" == "7" ]; then composer global require --update-no-dev sugared-rim/cs; fi
  - export PATH=$PATH:`composer global config bin-dir --absolute`

script:
  - composer travis
  - if [ "$TRAVIS_PHP_VERSION" == "7" ]; then composer lint; fi
